name: Packer Build

on:
  push:
    branches:
      - main
      - A04

  workflow_dispatch:
jobs:
  packer-build:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm run test:unit

      - name: Zip Web App
        run: zip -r webapp.zip .

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Set up Packer
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ vars.PACKER_VERSION }}

      - name: Run Packer init
        run: |
          cd packer 
          packer init ./custom-ami.pkr.hcl

      - name: Build Image
        id: build
        run: |
          cd packer 
          packer build \
            -var-file='./variables.pkr.hcl' \
            -var "AWS_REGION=${{ vars.AWS_REGION }}" \
            -var "AWS_PROFILE=${{ vars.AWS_PROFILE }}" \
            ./custom-ami.pkr.hcl

      - name: List files
        run: |
          ls -la
          find . -name "manifest.json"

      - name: Upload Manifest
        uses: actions/upload-artifact@v4
        with:
          name: packer-manifest
          path: manifest.json
