name: Packer CI

on:
  pull_request:
    branches:
      - main

jobs:
  packer-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip Web App
        run: zip -r webapp.zip .

      - name: Set up Packer
        uses: hashicorp/setup-packer@main
        with:
          packer_version: ${{ vars.PACKER_VERSION }}

      - name: Change directory to Packer
        run: cd packer

      - name: Run Packer init
        run: packer init custom-ami.pkr.hcl

      - name: Run Packer fmt
        id: packer-fmt
        run: |
          if ! packer fmt -check=true custom-ami.pkr.hcl; then
            echo "Formatting check failed for custom-ami.pkr.hcl"
            exit 1
          fi
          if ! packer fmt -check=true variables.pkr.hcl; then
            echo "Formatting check failed for variables.pkr.hcl"
            exit 1
          fi

      - name: Run Packer validate
        run: |
          if ! packer validate -var-file=variables.pkr.hcl custom-ami.pkr.hcl; then
            echo "Validation failed for custom-ami.pkr.hcl"
            exit 1
          fi
