name: Packer CI

on:
  pull_request:
    branches:
      - main

jobs:
  packer-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Packer
        uses: hashicorp/setup-packer@main
        with:
          packer_version: ${{ vars.PACKER_VERSION }}

      - name: Run Packer fmt
        id: packer-fmt
        run: |
          packer fmt -check=true ./packer/custom-ami.pkr.hcl

      - name: Run Packer validate
        run: |
          packer validate ./packer/custom-ami.pkr.hcl
